root: true

env:
  node: true
  es6: true

extends:
  - eslint:recommended
  - plugin:vue/recommended
  - plugin:prettier/recommended

parserOptions:
  parser: babel-eslint

rules:
  no-unused-vars:
    - 2
    - vars: all
      args: none
  vue/no-v-html: off
  prettier/prettier:
    - error
    - trailingComma: none
