name: build and deploy Gridsome to GitHub Pages automatically

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Install Node.js
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      
      # Install @gridsome/cli
      - name: Install Gridsome CI
        run: |
          npm install @gridsome/cli -g

      # Use GitHub Actions' cache to shorten build times and decrease load on servers
      - name: Check Cache
        uses: actions/cache@v1
        id: cache-dependencies
        with:
          path: node_modules
          key: ${{ runner.OS }}-${{ hashFiles('**/package-lock.json') }}

      # Install dependencies if there is no cache ()
      - name: Install Dependencies
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: |
          npm install
      
      # Build Gridsome and push it to gh-pages
      - name: Build and Deploy Gridsome
        run: |
          npm run build
          cd dist
          git init
          git config user.name "${{ GITHUB_ACTOR }}"
          git config user.email "${{ GITHUB_ACTOR }}@users.noreply.github.com"
          git add .
          git commit -m "Gridsome build from Action ${{ GITHUB_SHA }}"
          git push --force --quiet "https://${{ secrets.JEKYLL_PAT }}@github.com/${{ GITHUB_REPOSITORY }}.git" master:gh-pages